# Generated by Django 4.2.7 on 2024-05-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_category_woman'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='image',
            field=models.TextField(default='https://static.independent.co.uk/s3fs-public/thumbnails/image/2014/07/23/20/pg-38-rosie-riveter-1.jpg?width=1200'),
        ),
    ]
